"""Interactive smoke test against an unconfigured dev server; never sends external leads."""
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
BASE=os.environ.get('QA_DEV_URL','http://localhost:3000')
with sync_playwright() as pw:
    executable=next((Path(os.environ['LOCALAPPDATA'])/'ms-playwright').glob('chromium-*/chrome-win64/chrome.exe'))
    browser=pw.chromium.launch(executable_path=str(executable))
    context=browser.new_context(viewport={'width':360,'height':800},reduced_motion='reduce')
    context.add_init_script("localStorage.setItem('sd-consent-v1','essential')")
    page=context.new_page()
    for route,kind in [('/contato','contato'),('/suporte','suporte'),('/produtos/veraview-x800','produto')]:
        page.goto(BASE+route)
        form=page.locator('form')
        form.locator('input[name=name]').fill('QA Scientific')
        form.locator('button[type=submit]').click()
        expect(page.locator('#'+kind+'-email-error')).to_be_visible()
        expect(form.locator('input[name=name]')).to_have_value('QA Scientific')
        form.locator('input[name=phone]').fill('()--------')
        form.locator('input[name=email]').fill('qa@example.invalid')
        form.locator('input[name=consent]').check()
        form.locator('button[type=submit]').click()
        expect(page.locator('#'+kind+'-phone-error')).to_have_text('Informe um telefone válido com DDD')
        form.locator('input[name=phone]').fill('(31) 99999-9999')
        form.locator('button[type=submit]').click()
        expect(page.get_by_text('Pedido registrado',exact=True)).to_be_visible()
        print('dev validation + success:',kind,flush=True)
    page.goto(BASE+'/orcamento?produto=veraview-x800')
    expect(page.locator('input[name=equipment]').first).to_be_checked()
    page.get_by_role('button',name='Continuar',exact=True).click()
    page.get_by_role('button',name='Continuar',exact=True).click()
    expect(page.locator('#operation-error')).to_be_visible()
    page.locator('input[name=operation]').first.check()
    page.get_by_role('button',name='Continuar',exact=True).click()
    page.locator('input[name=timeline]').first.check()
    page.get_by_role('button',name='Continuar',exact=True).click()
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.get_by_role('button',name='Enviar pedido de orçamento',exact=True).click()
    expect(page.locator('#email-error')).to_be_visible()
    page.locator('input[name=name]').fill('QA Orçamento')
    page.locator('input[name=phone]').fill('31999999999')
    page.locator('input[name=email]').fill('qa@example.invalid')
    page.locator('input[name=consent]').check()
    page.get_by_role('button',name='Voltar',exact=True).click()
    expect(page.locator('input[name=timeline]').first).to_be_checked()
    page.get_by_role('button',name='Continuar',exact=True).click()
    expect(page.locator('input[name=name]')).to_have_value('QA Orçamento')
    page.get_by_role('button',name='Enviar pedido de orçamento',exact=True).click()
    expect(page.get_by_text('Pedido de orçamento registrado',exact=True)).to_be_visible()
    print('wizard: prefill, four steps, validation, back, retained input, success',flush=True)
    # Dialog keyboard flow and same-page navigation.
    page.goto(BASE+'/contato')
    page.get_by_role('button',name='Abrir menu',exact=True).click()
    dialog=page.get_by_role('dialog',name='Menu principal')
    expect(dialog).to_be_visible()
    page.keyboard.press('Shift+Tab');assert dialog.evaluate('(e)=>e.contains(document.activeElement)')
    page.keyboard.press('Escape');expect(dialog).to_have_count(0)
    expect(page.get_by_role('button',name='Abrir menu',exact=True)).to_be_focused()
    page.get_by_role('button',name='Abrir menu',exact=True).click()
    dialog.get_by_role('link',name='Contato',exact=True).click();expect(dialog).to_have_count(0)
    # Gallery responds to arrow keys.
    page.goto(BASE+'/produtos/veraview-x800')
    tabs=page.get_by_role('tab');tabs.first.focus();page.keyboard.press('ArrowRight');expect(tabs.nth(1)).to_have_attribute('aria-selected','true')
    assert 'Veraview%20X800' in page.locator('.wa-float').get_attribute('href')
    print('mobile menu, keyboard gallery, contextual WhatsApp: passed',flush=True)
    # Existing catalog history regression.
    page.goto(BASE+'/produtos')
    page.get_by_role('group',name='Fabricante',exact=True).get_by_role('button',name='Morita').click()
    expect(page).to_have_url(__import__('re').compile('marca=morita'))
    page.get_by_role('group',name='Categoria',exact=True).get_by_role('button',name='Endodontia').click()
    expect(page).to_have_url(__import__('re').compile('categoria=endodontia'))
    page.go_back();expect(page).to_have_url(BASE+'/produtos?marca=morita')
    print('catalog filter + browser history: passed',flush=True)
    # Production without delivery configuration must fail visibly and preserve input.
    page.goto('http://localhost:3001/contato')
    for name,value in [('name','QA Falha'),('phone','31999999999'),('email','qa@example.invalid')]: page.locator(f'input[name={name}]').fill(value)
    page.locator('input[name=consent]').check();page.locator('button[type=submit]').click()
    expect(page.get_by_text('Não conseguimos registrar seu pedido agora.',exact=False)).to_be_visible()
    expect(page.locator('input[name=name]')).to_have_value('QA Falha')
    print('production failure state: passed',flush=True)
    # Consent: essential, persistence, revoke, all; no analytics without configuration.
    fresh=browser.new_context(viewport={'width':360,'height':800},reduced_motion='reduce')
    cookie=fresh.new_page();cookie.goto(BASE)
    cookie.get_by_role('button',name='Somente essenciais').click()
    expect(cookie.get_by_role('dialog',name='Cookies e privacidade')).to_have_count(0)
    cookie.reload();expect(cookie.get_by_role('dialog',name='Cookies e privacidade')).to_have_count(0)
    cookie.get_by_role('button',name='Gerenciar cookies').click()
    cookie.get_by_role('button',name='Aceitar todos').click()
    expect(cookie.get_by_role('dialog',name='Cookies e privacidade')).to_have_count(0)
    assert cookie.evaluate("localStorage.getItem('sd-consent-v1')")=='all'
    assert cookie.locator('script[src*="googletagmanager"]').count()==0
    blocked=browser.new_context(reduced_motion='reduce')
    blocked.add_init_script("Storage.prototype.getItem=Storage.prototype.setItem=()=>{throw new Error('blocked')}")
    bp=blocked.new_page();bp.goto(BASE);bp.get_by_role('button',name='Somente essenciais').click();expect(bp.get_by_role('dialog',name='Cookies e privacidade')).to_have_count(0)
    print('cookie accept, essential, revoke, blocked storage: passed',flush=True)
    browser.close()

